### ISSUE TITLE
$err variable undefined

### ISSUE THREAD

**Issue by luisske** [Korak-997/schule#2]
## Problem
the variable `$err` is never set or initialized in the program

https://github.com/Korak-997/schule/blob/f322206775d48a448e86f0065f6ff77c93902bf2/LF08/mathe/index.php#L129-L131

## Result
- throwing an error message after generating the tasks

**Comment by Korak-997** [comment]
It was a small bug , i simply forgot to refactor the code after some changes :smile: now it is fixed with last commit
